import os


REDIS_HOST = os.environ.get('OPENSHIFT_REDIS_DB_HOST', '127.0.0.1')
REDIS_PORT = os.environ.get('OPENSHIFT_REDIS_DB_PORT', '6379')
REDIS_PASSWORD = os.environ.get('OPENSHIFT_REDIS_DB_PASSWORD')

KEY_VERSION = 1
FLUSH_REDIS = 'FLUSH_REDIS'
